### ISSUE TITLE
NullPointerException out of convert() function

### ISSUE THREAD

**Issue by zhihaoy** [jenkinsci/opencover-plugin#14]
### Jenkins and plugins versions report

Jenkins 2.346.3

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows Server agents

### Reproduction steps

Calling
```groovy
script.publishCoverage(adapters: [script.opencoverAdapter(mergeToOneReport: true, path: 'some/path/*.xml')],
                       sourceFileResolver: script.sourceFiles('NEVER_STORE'),
                       failNoReports: false)
```
from a script

### Expected Results

Results published.

### Actual Results

```
Also:   hudson.remoting.ProxyException: java.lang.NullPointerException
		at io.jenkins.plugins.opencover.OpenCoverReportAdapter.convert(OpenCoverReportAdapter.java:70)
		at io.jenkins.plugins.coverage.adapter.CoverageReportAdapter.getResult(CoverageReportAdapter.java:57)
		at io.jenkins.plugins.coverage.CoverageProcessor.convertToResults(CoverageProcessor.java:383)
		at io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport(CoverageProcessor.java:108)
		at io.jenkins.plugins.coverage.CoveragePublisher.perform(CoveragePublisher.java:99)
		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
```

### Anything else?

Changing the `path` argument to `path/to/clover.xml` makes no difference. The file is there and can be archived. The file displays fine in the old `clover` plugin. The file is converted from Bullseye `.cov` file using `bullshtml.jar` .

**Comment by jonesbusy** [comment]
Can you attach an opencover XML file that raise this NullPointer ?

**Comment by zhihaoy** [comment]
Is this plugin for https://github.com/OpenCover/opencover?
If so, I think I understand why... I was looking for a replacement for the built-in `clover` plugin. Not the same format.

**Comment by jonesbusy** [comment]
Yes it's for .NET OpenCover (It's a bit abandonned now, but many legacy .NET project are still using it).

Closing then
